plex:
  url: "http://localhost:32400"
  token: "PLEX_TOKEN"
  movie_library_name: "Movies"
  delete_preference: "largest_file"  # Options: smallest_file, oldest, newest
  preserve_quality: [] # Files with these keywords won't be deleted
